spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet_transfer
    username: wallet_user
    password: wallet_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.springframework: INFO
    com.wallet.transfer: DEBUG
ledger-api:
  host: 'http://ledger-service:8081'
  transfer:
    api: '/api/ledger/transfer'

# Example for loading environment variables in Docker Compose or shell:
# export POSTGRES_PASSWORD=dev_pass
# or in Docker Compose:
# environment:
#   - POSTGRES_PASSWORD=dev_pass
