name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build commons JAR
        run: mvn clean install -DskipTests -f common/pom.xml

      - name: Build transfer-service
        run: mvn clean install -DskipTests -f transfer-service/pom.xml
      - name: Build with Maven
        run: mvn -B clean verify -DskipTests

